// This file was generated by Prisma
// Required deps:
// npm install --save-dev prisma @prisma/config dotenv

import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  engine: "classic",

  datasource: {
    url: env("DATABASE_URL"),
  },
});
