// This file was generated by Prisma
// Required deps:
// npm install --save-dev prisma @prisma/config dotenv

import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

// Helper to safely get DATABASE_URL without throwing if not found
const getDatabaseUrl = () => {
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }
  
  // Try to load from env, but don't throw if not found
  try {
    return env("DATABASE_URL");
  } catch {
    // Return empty string to allow build to proceed
    // The actual DATABASE_URL will be set at runtime
    return "";
  }
};

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  datasource: {
    url: getDatabaseUrl(),
  },
});
