// This file was generated by Prisma
// Required deps:
// npm install --save-dev prisma @prisma/config dotenv

import "dotenv/config";
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: "prisma/migrations",
  },

  engine: "classic",

  datasource: {
    // Use process.env directly to support Render production builds
    // where .env file is not available but DATABASE_URL is set in environment
    url: process.env.DATABASE_URL || env("DATABASE_URL"),
  },
});
